version: "3.8"
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    container_name: app
    command: bundle exec rerun 'ruby app.rb -o 0.0.0.0 -p 4567'
    ports:
      - "4568:4567"
    volumes:
      - .:/code